config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end


  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.invalid?
    flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
    redirect_to root_path
  end

  def about
  end

  def new
    @recipe = Recipe.new
  end
  private

  def recipe_params
    params.require(:recipe).permit(:ingredients, :cooking_method, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="row">
      
    </header>
    <hr />
    <br class="clear" />

    <div class="container">
      <%= yield %>
    </div>

    <div class="footer">
      
    </div>

  </body>
</html>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
  <div class="booyah-box col-10 offset-1">
  <h1><%= recipe.name %></h1>
  </br>
  <h2><%= recipe.ingredients %></h2>
  </br>
  <h3><%= recipe.cooking_method %></h3>
  </div>
      
<% end %>

<%= link_to 'Create', new_recipe_path(@recipes), class: 'btn btn-secondary' %>



app/views/recipes/new.html.erb
<h1>Enter Your Recipe</h1>
<%= simple_form_for @recipe do |f| %>
  <%= f.input :name %>
  <%= f.input :ingredients %>
  <%= f.input :cooking_method %>
  <%= f.button :submit %>
<% end %>
